# Preload the specific image into RAM
preload = ~/dotfiles/backgrounds/artemis2_lunar_flyby_eclipse_integrity.jpg

# Set the wallpaper for all monitors (empty monitor name)
wallpaper = , /home/toni/dotfiles/backgrounds/artemis2_lunar_flyby_eclipse_integrity.jpg

# Optional: Disable splash and enable IPC
splash = false
ipc = on
