general {
    lock_cmd = pidof hyprlock || hyprlock --grace 20
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 420
    on-timeout = loginctl lock-session
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
}
