# Preload the specific image into RAM
preload = ~/dotfiles/backgrounds/mojave.jpg

# Set the wallpaper for all monitors (empty monitor name)
wallpaper = , /home/toni/dotfiles/backgrounds/mojave.jpg

# Optional: Disable splash and enable IPC
splash = false
ipc = on
